[package]
name = "pore"
version = "0.1.0"
authors = ["Josh Gao <josh@jmgao.dev>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
lazy_static = "1.4.0"

log = "0.4"
anyhow = "1.0"
futures = "0.3"
indoc = "1.0"

serde = "1.0"
serde_derive = "1.0"
toml = "0.5"

regex = "1"
serde_regex = "1"

# manifest::serialize::serializer passes a quick-xml value to minidom, so the quick-xml version
# must match the version needed by minidom.
quick-xml = "^0.17"
minidom = "=0.12.0"

clap = "2.34.0"
maplit = "1.0.2"

chrono = "0.4.19"
copy_dir = "0.1.2"
dirs = "4.0.0"
shellexpand = "2.1.0"
pathdiff = "0.2.1"
url = "2.2.2"
walkdir = "2.3.2"

git2 = "0.13.25"

console = "0.15.0"
progpool = "0.2"

tracing_facade = "0.1"
tracing_chromium = "0.1"
